# Generated by Django 4.2.14 on 2024-07-11 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last activity'),
            preserve_default=False,
        ),
    ]
